image: mcr.microsoft.com/dotnet/core/sdk:6.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test --filter TestCategory=Unit