image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
   SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
   GIT_DEPTH: "0" 

stages:
  - build
  - test
  - sonarcloud-check

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop