name: .NET Tests and SonarCloud

on:
  push:
    branches:
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release

    - name: Upload test results to SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        sonarcloud.organization: stanstudenthonk
        sonarcloud.projectKey: StanStudentHonk_Bioscasus
        sonarcloud.token: ${{ secrets.SONARCLOUD_TOKEN }}
        sonarcloud.scanner.projectBaseDir: ${{ env.GITHUB_WORKSPACE }}
        sonarcloud.scanner.testExecutionReportPaths: "**/TestResults/*.trx"
